### ISSUE TITLE
New RPCs for Coloured Coin Feature

### ISSUE THREAD

**Issue by Naviabheeman** [chaintope/tapyrus-core#135]
The following new RPCs are needed to make using coloured coins easier in Tapyrus.
After PR #127 and PR #128 we will be able to send coloured coins using sendToAddress RPC. We need more RPCs to create and burn tokens.

1. **issuetoken** <token_type_1> <token_value> <script_Pubkey>
**issuetoken** <token_type 2,3> <token_value> <from_txid, index> 
 _Output_ - color_id, txid
2. **transfertoken** <to_address> <token_value> 
similar to sendtoaddress. so internally we can just call sendToAddress
_Output_ - txid
3. **burntoken**  <color_id>  <token_value> 
_Output_ - txid
4. **getcolor** <token_type> <txid, index> or <script_PubKey>  
 _Output_ - color_id
 5.  **reissuetoken**  <color_id>  <token_value>
Output - txid

**Comment by azuchi** [comment]
> 3. **burntoken**  <token_value>

Don't you need a colorid to identify which token to burn?

**Comment by Yamaguchi** [comment]
We need an additional Rpc to reissue for REISSUABLE token?

```
5. reissuetoken <colorid> <token_value>
Output - txid
```

**Comment by Naviabheeman** [comment]
> > 1. **burntoken**  <token_value>
> 
> Don't you need a colorid to identify which token to burn?

right! I changed the description
