### ISSUE TITLE
Add a new RPC that broadcast multiple txs atomically

### ISSUE THREAD

**Issue by rantan** [chaintope/tapyrus-core#151]
# Motivation

Regarding applications that use transactional databases like RDB and Tapyrus Core, application developers would want to deal with any modification to DB and blockchain atomically. 
However, we have `sendrawtransaction` RPC that is for broadcasting one tx at once. So that, if developers want to broadcast multiple txs in a transaction process, developers need to create a complex recovery logic or just pray.

# Interface to the new RPC

`sendmultiplerawtransaction ["tx", ...] ( maxfeerate )`

## Argument #1 - txs

Type: json array, required

[
  "tx",    (string) hex string of a raw transaction
  ...
]

## Argument #2 - maxfeerate

Type: numeric or string, optional, default=0.10

Reject transactions whose fee rate is higher than the specified value, expressed in BTC/kB.
Set to 0 to accept any fee rate.
This is the same as `sendrawtransaction` 's one.

## Result

An array of txid that are broadcasted.

**Comment by azuchi** [comment]
@rantan You can use `testmempool` accept instead of implementing this atomicity.

https://bitcoincore.org/en/doc/0.17.0/rpc/rawtransactions/testmempoolaccept/

**Comment by rantan** [comment]
We have two options for this kind of case.

1. Commit database transaction for each tx
2. Use `testmempoolaccept` before broadcasting.
