### ISSUE TITLE
Unexpected error occurs if invalid parameter is specified in getnewaddress RPC.

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-core#155]
The address type has been replaced by color id in the #150 change. However, when I run it with the address type specified, I get the following error.

```
$  ./tapyrus-cli getnewaddress '' legacy
error code: -1
error message:
CDataStream::read(): end of data: iostream error
```

it should be correct to raise the following error.

```cpp
throw JSONRPCError(RPC_INVALID_PARAMETER, "Invalid color parameter.");
```

**Comment by Naviabheeman** [comment]
PR #156 fixes this issue.
