### ISSUE TITLE
Create getting started documents for Tapyrus users

### ISSUE THREAD

**Issue by rantan** [chaintope/tapyrus-core#18]
Now, we don't have documents for helpful to start. So, it is really hard to got to run tapyrus core, and i heard from somebodies already.

I think we need to prepare documents for:

* Building Tapyrus Core.
     * `doc/build-xxx.md` is existing, but it's not tested.
     * It can base `build-test.sh` and ci setting in `.github/workflows/*.md`. but these are not easy to read 😢 
* Run in `regtest` mode
     * This will help developping with tapyrus.
* Run as testnet node
     * We have testnet network, but informations about that doesn't not appear in public. 
     * Actually, you can startup tapyrus testnet node with following arguments on `v0.2.0`.

tapyrus.conf (This file is able to be put as well as bitcion.conf to be.)
```
testnet=3
signblockpubkeys=033cfe7fa1be58191b9108883543e921d31dc7726e051ee773e0ea54786ce438f8020464074b94702e9b07803d247021943bdcc1f8700b92b66defb7fadd76e80acf02cbe0ad70ffe110d097db648fda20bef14dc72b5c9979c137c451820c176ac23f
signblockthreshold=2
```

genesis.dat (This file should be placed at top of data directory. For example `~/.tapyrus/genesis.dat` if `~/.tapyrus` is data directory.)
```
0100000000000000000000000000000000000000000000000000000000000000000000002e4533a0ccb1c1b83a641ce00656d3d234e362ab2ce0d6d69eaaba1edceb9e962f69b65cb127339d5d8da08d50f6d4deb37b46157123dbe5fb0a30a641af68e70c3d285d0346304402201e9de308c52cfc760c9eb5a1638857563c39791a77bd3b4c53dcd26b4d02e8480220542963fe20dbedd31c609f8393cb68e4b80c4e849fcddf7a0a2dddaac4ce2e134630440220295288205c39d933dd7c236011857cf3b0147e226154afc5c44421a38cb0a77102202c580fdf814904ed3f17fce8f545ba66aa3ebd9a00eb7205371ee3de895e2a0346304402200f9301b705c64a5fb5cb9ecb8cf4498291142b93491cb560e36db6145f60d6e002200572b51df4e1397340a1487f9f8b35e07730055a2d4d9a83e0954ff22a8bc599010100000001000000000000000000000000000000000000000000000000000000000000000000000000240102210276d7a1b83fd97b8751d2b82e1f7a89dcd23a5b3f5cc2798083ad6f775018102effffffff0100f2052a010000001976a914a941c2ccebe78a5a1348dddd42362b588cb563b588ac00000000
```

**Comment by rantan** [comment]
I think it is better to create a document for starting up brand new network on tapyrus core, but it is after #17 is done.

**Comment by Naviabheeman** [comment]
Getting started documentation is in [PR#22]( https://github.com/chaintope/tapyrus-core/pull/22/files)

**Comment by Naviabheeman** [comment]
Leaving this open as a reminder to update getting started document after #17
