### ISSUE TITLE
Modify transaction validation rule for txs which issue colored coins

### ISSUE THREAD

**Issue by rantan** [chaintope/tapyrus-core#191]
[Here](https://github.com/chaintope/tapyrus-core/blob/master/src/validation.cpp#L1050) checks txs which issues colored coin have enough TPC amount in their inputs.

It intends to allow any positive value of TPC to issue new tokens. So it is enough to satisfy below condition

```cpp
 tpcin - tpcout - ::minRelayTxFee.GetFee(nSize) <= 0
```

However it is defferent from this. So the current implementation should be modify to the above condition.

**Comment by Naviabheeman** [comment]
PR #192 fixes this
