### ISSUE TITLE
Incorrect balance in wallet

### ISSUE THREAD

**Issue by Naviabheeman** [chaintope/tapyrus-core#197]
Tapyrus wallet is assuming the coinbase transactions which are not in its memory pool as unconfirmed. It needs to be reviewed and fixed. Wallet balance is not accurate because of this.

**Comment by azuchi** [comment]
> I am able to simulate the same inconsistency whenever I kill the GUI and start again without "-reindex"

@Naviabheeman This meas `-reindex` required every time when start the GUI?

**Comment by Naviabheeman** [comment]
When tapyrus-qt is closed from the GUI the index and blocks are flushed. I verified that there is no need to reindex. Only when I kill the process from within the debugger this happens.
