### ISSUE TITLE
Release schedule for 0.3.0

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-core#21]
Here is a proposed release schedule for 0.3.0, the next major release of Tapyrus Core.

The following tasks are required for release:

- [x] Create "Getting started" document.
- [x] Integration test of Tapyrus Core and Tapyrus Signer aggregated signature feature.
- [x] Create release notes for 0.3.0.
- [x] Release tagging.
- [x] Reset testnet.
- [x] Publish testnet faucet.

**Comment by rantan** [comment]
Regarding release note, we are going to clean up pre-forked notes and add new release-note for tapyrus.

**Comment by rantan** [comment]
I've created release candidate branch as [v0.3.0](https://github.com/chaintope/tapyrus-core/tree/v0.3.0).

**Comment by rantan** [comment]
The taging is going to be done when we publish release draft on github.

**Comment by rantan** [comment]
These are also needed for Tapyrus-Signer.
* Create release notes for 0.3.0.
* Release tagging.

**Comment by rantan** [comment]
All release tasks are done!
