### ISSUE TITLE
Create tapyrus.conf as a reference configuration file

### ISSUE THREAD

**Issue by oshikawatkm** [chaintope/tapyrus-core#210]
Change bitcoin.conf under [tapyrus-core/share/examples](https://github.com/chaintope/tapyrus-core/tree/master/share/examples) to tapyrus.conf.
The contents of tapyrus.conf should include tapyrus-specific parameters and explanations for reference when building the tapyrusd node.

**Comment by Naviabheeman** [comment]
PR #218 added
