### ISSUE TITLE
Add generatekey command to tapyrus-genesis cli

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-core#211]
When using Tapyrus Core in dev mode, the options `-signblockpubkey` and `-signblockprivatekey` must be specified. I can generate these keys using an external library, but it is more useful to have a command in tapyrus-genesis that generates the key pair. So let's add a `generatekey` command that outputs a private key in WIF format and a compressed public key in hex format.

**Comment by Naviabheeman** [comment]
The genesis block creation would be two steps:
`tapyrus-genesis generatekey -dev`
`tapyrus-genesis -dev -signblockpubkey=<pubkey> -signblockprivatekey=<priv-wif>`

or 

`tapyrus-genesis generatekey -dev ` which gives all three pub key, privacy_wif and genesis block hex?

**Comment by azuchi** [comment]
completed by #220.
