### ISSUE TITLE
Error log "CBlockPolicyEstimator::Read(): up-version (1000000) fee estimate file" should be remove

### ISSUE THREAD

**Issue by rantan** [chaintope/tapyrus-core#212]
```
2022-07-05T18:45:07Z ERROR: CBlockPolicyEstimator::Read(): up-version (1000000) fee estimate file
```

We can find this error log always in `debug.log` when we start tapyrus core.
I think it is Bitcoin Core legacy and meanless in Tapyrus Core. So, we can eliminate the code that shows the error log.
What do you think?

# Details

The place where puts the log is here https://github.com/chaintope/tapyrus-core/blob/05cdfa260591aefb122af4078818d2a916455d32/src/policy/fees.cpp#L932.

And the condition is here https://github.com/chaintope/tapyrus-core/blob/05cdfa260591aefb122af4078818d2a916455d32/src/policy/fees.cpp#L931

`CLIENT_VERSION` is 50100  in v0.5.1 at the latest.
`nVersionRequired` is fixed to 1000000.
`1000000` is from a file but I guess the original value is from `ESTIMATOR_FILE_VERSION` and the value of `ESTIMATOR_FILE_VERSION` is fixed to `1000000`.

Probably, the error log would be reported until Tapyrus Core version reaches up to 1.0.0. 
So, I think the log is meanless.

**Comment by Naviabheeman** [comment]
Yes, I think the initial value of ESTIMATOR_FILE_VERSION was set assuming that our first release would be v1.0.0 but we are still at v0.5.1.
 So how can we fix this?  Remove only the error message or change ESTIMATOR_FILE_VERSION to 0.5.1.
