### ISSUE TITLE
Specifying an invalid scriptPubkey in issuetoken RPC cause a segmentation fault.

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-core#221]
If run issuetoken with an invalid scriptPubkey, such as the following, I got a segmentation fault.

```
$ tapyrus-cli issuetoken "1" "100" h
```

**Comment by Naviabheeman** [comment]
PR #224 fixes this. Other RPCs like transfer token, burn token and reissue token do not have unvalidated inputs. These are safe.
But getcolor RPC takes similar inputs as issuetoken. It does not cause segmentation fault when invalid inputs are given. However it returns a colorId even for incorrect inputs like the one above. I guess this is fine as getcolor only returns a hash. Please comment if you would prefer an error in case of invalid script or taxied in getcolor too.

**Comment by azuchi** [comment]
> However it returns a colorId even for incorrect inputs like the one above. I guess this is fine as getcolor only returns a hash. Please comment if you would prefer an error in case of invalid script or taxied in getcolor too.

If there is an unexpected input, it is better to make an error. 

BTW, since `getcolor` does not handle wallet information, it does not need to be Wallet RPC.
