### ISSUE TITLE
Add option to listunspent to filter only token UTXO

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-core#222]
Currently `listunspent` returns UTXO for TPC and tokens; it is possible to distinguish between the two by whether `token="TPC"` or not, but an option to return only tokens would be useful.

So why not add `only_token: true` to the current `query_options`? The default behavior would remain the same as now, but if true, only  tokens would be returned.

**Comment by Naviabheeman** [comment]
#227 implements this filter
