### ISSUE TITLE
Change lock period for coinbase coin

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-core#30]
Coinbase coins require 100 block confirmation to spend it. But in tapyrus, block signature meas finality, so coinbase coin can be spend from next block.

**Comment by Naviabheeman** [comment]
PR#50 implements this.

Another follow up question is, do we still need support for blockchain reorg? We still have the support for storing transaction undo data for every transaction (except Coinbase) in files to allow successful reorg.

**Comment by Naviabheeman** [comment]
> Another follow up question is, do we still need support for blockchain reorg? We still have the support for storing transaction undo data for every transaction (except Coinbase) in files to allow successful reorg.

Resolving this issue now as we do not need to change re-org.
