### ISSUE TITLE
Upgrade the base docker image to Ubuntu 22.04

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-core#303]
Upgrade tapyrus-builder and tapyrusd container images to Ubuntu 22.04 base.

**Comment by Naviabheeman** [comment]
Sorry, last week I tried to build a builder container test version without realizing that the base was still ubuntu20! My mistake.  
Fixed it in #304
And while doing these I noticed new warnings from GitHub action. I'll create a separate PR for that.

**Comment by azuchi** [comment]
@Naviabheeman I merged #304.  Then, you need to create a 22.04-based tapyrus-builder image and reference that new image in tapyrusd's Dockerfile.

**Comment by azuchi** [comment]
Finished by #304 and #306.
