### ISSUE TITLE
Show aggregated public key  in the output item of getblockchaininfo.

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-core#31]
Add the aggregate public key used by the current chain to verify the block to the output of `getblockchaininfo` RPC.

**Comment by Naviabheeman** [comment]
Now in Tapyrus Core we store aggPubkey as a single element in chainparams. I think we should change this into a list/stack. When federation management is implemented we can append the new aggPubkey to this list. getblockchaininfo RPC can be enhanced to display the full list of aggPubkeys and federation change block heights.

**Comment by azuchi** [comment]
ACK. This task itself can be at the timing of adding the feature of federation management.

**Comment by Naviabheeman** [comment]
One more clarification about what we need to report as block height. In this output 'n' is the block height where 'aggregate pubkey' change is accepted in Tapyrus Core or next block where the new federation starts signing blocks?
| Aggregate pubkey |    block height |
| :---: | :---: |
| genesis  aggPubkey    |          0  |
| new aggPubkey2   |          n |

**Comment by rantan** [comment]
I think it should be the block which has an aggregated public key. Because the `changing` would be happened there.

And a field name of the block height is good to have one more word which explains it is what kind of block height such as `changed`, `assigned`.

**Comment by azuchi** [comment]
> next block where the new federation starts signing blocks

is right.

**Comment by rantan** [comment]
@Naviabheeman Can you show me an example of `getblockchaininfo` output which is applied changes for this issue If you have any idea already?

I want to use aggregated public key information in tapyru-signerd.

**Comment by Naviabheeman** [comment]
@rantan I'm planning to make it a list of key-value pairs like this:

>{
  "chain": "1939510133",
  "mode": "prod",
  "blocks": 17540,
  "headers": 17540,
  "bestblockhash": "709720a6379b47ec66a3c8955138553dc1a13ea6c390d46e9af0dae0dce41044",
  "mediantime": 1585555979,
  "verificationprogress": 2.200173736789804e-15,
  "initialblockdownload": false,
  "size_on_disk": 6300418,
  "pruned": false,
  "warnings": ""
  _**"aggregatePublicKeys":
  {[
    "key1":height1,
    "key2":height2
  ]}**_
}

Please let me know if you have other suggestions.

**Comment by rantan** [comment]
I think it should be such as below:

```json
"aggregatePublicKeys": {
  "key1":height1,
  "key2":height2
}
```

If it is json.

**Comment by Naviabheeman** [comment]
implementation in PR #70
