### ISSUE TITLE
Relaxing standard rules

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-core#40]
Currently, standard rules restrict script patterns(e.g. P2PKH, P2SH, bare multisig). So if create an arbitrary contract, it must be in P2SH format.

P2SH allows the commission to be transferred from the sender to the recipient, but this is not necessarily enforced and should give the user a choice.

Then, in Tapyrus, relax existing standard rules so that you can send funds to any script. This will make future covenants more convenient.

**Comment by Naviabheeman** [comment]
Fixed by https://github.com/chaintope/tapyrus-core/pull/48
