### ISSUE TITLE
Change coin unit notation

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-core#43]
Because tapyrus is based on Bitcoin, the notation of coin units is BTC / satoshi. Therefore, change this to TPC / tapyrus.

**Comment by winnie-chaintope** [comment]
<img width="780" alt="Screenshot 2020-03-10 at 4 18 10 PM" src="https://user-images.githubusercontent.com/61957420/76293012-40aae680-62eb-11ea-9393-29fb342ba653.png">

azuchi san, 
for string like "Bitcoins" and shortform of satoshi "SAT"
what should i replace with?

**Comment by azuchi** [comment]
HI @winnie-chaintope 

> for string like "Bitcoins" and shortform of satoshi "SAT"
> what should i replace with?

let's replace `tap`.

**Comment by winnie-chaintope** [comment]
@azuchi san
for "Bitcoins" need to change to "Tapyruscoins" ?

**Comment by azuchi** [comment]
let's replace `TPC`.

**Comment by Naviabheeman** [comment]
fixed by https://github.com/chaintope/tapyrus-core/pull/55
