### ISSUE TITLE
Review Payment protocol, BIP70 support in Tapyrus.

### ISSUE THREAD

**Issue by Naviabheeman** [chaintope/tapyrus-core#44]
In Tapyrus-Qt unit tests,  BIP70 payment protocol is tested using hard coded base64 strings of x.509 certificates. These tests are failing after #39 as Tapyrus uses the network name "prod" but  "main" and "test" are encoded in the base64 test strings. Review BIP70 and if we need to continue using this protocol, try to make it **networkid** based. Update the test certificates accordingly. 

From bitcoin version 0.19, [#15584](https://github.com/bitcoin/bitcoin/pull/15584), BIP70 Payment protocol code is not built into Bitcoin-Qt by default as it is considered unsafe. This comment describes the problems : https://github.com/bitcoin/bitcoin/pull/15584#issuecomment-534767981.  
If BIP70 is disabled, protobuf dependency can also be disabled. (https://github.com/bitcoin/bitcoin/pull/16871)

**Comment by azuchi** [comment]
I see, disable BIP70.

**Comment by Naviabheeman** [comment]
added in #53
