### ISSUE TITLE
Federation Management - Tapyrus Core

### ISSUE THREAD

**Issue by Naviabheeman** [chaintope/tapyrus-core#60]
To support federation management feature, we need Tapyrus Core to support updating aggregate pubkey when federation changes.

Now Aggregate pubkey in CFederationParams is populated at startup from "aggPubKey" in genesis block header. When newer blocks contain a new  "aggPubKey" it implies that a federation change has happened. So Tapyrus Core should support changing the Aggregate pubkey during block validation (after block proof and other elements in the block are verified)

**Comment by Naviabheeman** [comment]
This change has some hidden scenarios. We need to make sure we cover these and test them thoroughly:
`CFederationParams` is being changed to contain a list os `struct` with aggpubkey and block height. We need to keep this list in synch with the main chain( longest chain).
1) **reading block from disk** -  After a block is accepted and written to disk it is read from the disk when the block is requested by another node. This step verifies the block header i.e proof. WE have to make sure that the correct aggpubkey is used for this proof validation. For a block at height 'n' we need to verify the proof using the latest aggregate pubkey at that height. (not the latest aggregate pubkey of the current tip)
2) **blockchain reorg** - When there is a blockchain reorg and the block with aggregate pubkey is removed from the longest chain, the corresponding changes to aggpubkey list should be removed from the list too.
3) **reading block from disk if block is not in the main chain** - in this case the block info is still available in the node. But the block height in the index is -1. We _**need not**_ verify the block proof of such blocks as the correct aggregate pubkey is not known. 


**Functional test:**

Simulate the following in the functional test
|Block | Scenario | Expectation |
|--| --| --|
|B0 | Genesis block | aggpubkey1 |
|B1 - B10| Generate 10 blocks with no aggpubkey | chain becomes longer|
|B11 | Create block - aggpubkey2 -  sign with aggpubkey1 | success - aggpubkey2 is added to the list|
|  B | Create block  -  sign with aggpubkey1 | failure - proof verification fails|
| B12 | Create block  -  sign with aggpubkey2 | success |
| B13 - B22 | Generate 10 blocks - no aggpubkey | chain becomes longer|
| B23 | Create block  with 1 valid transaction -  sign with aggpubkey2 | success |
| B |- Create block  with 1 invalid transaction -  sign with aggpubkey2 | failure |
| B |- Create block  with 1 invalid transaction and aggpubkey3  -  sign with aggpubkey2 | failure and aggpubkey3 is not added to the list|
| B24 | Create block  with 1 valid transaction and aggpubkey3-  sign with aggpubkey2 | success and aggpubkey3 is added to the list|
|B25 | Create block  with 1 valid transaction -  sign with aggpubkey3 | success |
| |Simulate Blockchain Reorg as follows| |
|B24 | Create block  with previous block hash = B23 -  sign with aggpubkey2 | success  - block is accepted but there is no re-org |
|B25 | Create block  with previous block hash = B24 -  sign with aggpubkey2 | success - block is accepted but there is no re-org |
|B26 | Create block  with previous block hash = B25 and aggpubkey4 -  sign with aggpubkey2 | success - there is a chain re-org|
|B | Create block with previous block hash = B26 -  sign with aggpubkey2 | failure - proof verification failed|
|B | Create block with previous block hash = B26 -  sign with aggpubkey3 | failure - proof verification failed
|B27 |Create block with previous block hash = B26 -  sign with aggpubkey4 | success|

test the output of RPC Getblockchaininfo before reorg and after reorg. Verify block aggpubkey and block height
1) Before reorg after B25 the expected output is
	aggpubkey1 = 0
	aggpubkey2 = 12
	aggpubkey3 = 26

1) After reorg after B27 the expected output is
	aggpubkey1 = 0
	aggpubkey2 = 12
	aggpubkey4 = 27

**Comment by rantan** [comment]
Hi, thank you for the clarification.

I have 2 worries.

1. It seems that this scenario doesn't cover "1. reading block from disk". It would be covered by other test cases?

2. Regarding "3. reading block from disk if block is not in the main chain". The orphan block has previous block header hash. So we can follow the aggregate public key for the block. Is this right?
I'm wondering if we don't verify the block proof, it might be a cause of DoS. 
ummm, or is it no problem because of the block should not relay to other node(not submitted node)?

**Comment by Naviabheeman** [comment]
> 1. It seems that this scenario doesn't cover "1. reading block from disk". It would be covered by other test cases?

It will be covered in the same test case. We discovered this scenario because of "getbestblockhash" and "getblock" RPC calls after each block. (getblock RPC invokes the reading from disk flow.) I'll elaborate in the comment above.
 
> 2. Regarding "3. reading block from disk if block is not in the main chain". The orphan block has previous block header hash. So we can follow the aggregate public key for the block. Is this right?
>    I'm wondering if we don't verify the block proof, it might be a cause of DoS.
>    ummm, or is it no problem because of the block should not relay to other node(not submitted node)?

In the scenario above B25 signed using aggpubkey3, if we read it from the disk after the reorg aggpubkey3 is lost in CFederationParams. We have to read the chain of previous blocks/indexes until we get the correct aggpubkey. First, this seems like a lot of effort for the rare case. Second, in the case of getblock RPC, trying to verify proof using a different pubkey causes DoS, as the block is not returned. We can just return the block without trying to verify the proof.

**Comment by Naviabheeman** [comment]
We came across another scenario during blockchain reorg.

> **G** - 1 - 2 - 3 - 4 - 5 - 6 - 7 - 8 - 9 - 10 - 11 - **12** - 13 - 14 -15 - 16 - 17 - 18 - 19 - 20 - 21 - 22 - 23 - 24 -**25** -26 - 27 - 28 - 29 - 30

In the chain above G, 12 and 25 are federation blocks.
Now when we try to create a fork, two cases arise:
1) Fork after all federation blocks: (forked blocks can be verified using the last aggpubkey)
               - F27-F28-F29-F30-F31
2) Fork before at least one federation block: (forked blocks must be verified using older aggpubkey tased on the fork and height)
             - F24 - F25

With our current implementation only case 1 can be handled correctly. To support case 2 we need to make our list more complex, aware of all fork in the chain. Do we need to support it?

**Comment by azuchi** [comment]
Thanks @Naviabheeman, How does case 2 work with current implementation?

**Comment by Naviabheeman** [comment]
currently we are assuming that all new blocks are expected at the end of the chain, so we use the last aggregate pubkey to verify the proof. In case 1, blocks are still accepted. But case 2 blocks fail proof validation.

**Comment by azuchi** [comment]
Basically signer is a trusted parties and they have agreed to change the federation in the federation block, so they wouldn't  create a block like case 2. As a result, the current implementation can be used.

**Comment by Naviabheeman** [comment]
PRs #68, #71, #72 implement this feature. 

Final implementation is:
1) **new federation block** -  We verify the proof using the aggregate pubkey based on block height. 
2) **reading block from disk** -  For blocks in main chain and not in main chain we verify the proof using the aggregate pubkey based on block height. 
3) **blockchain reorg** - Reorg of blocks before the last federation block is not allowed. We do not remove aggregate pubkeys that were added earlier. As a result InvalidateBlock RPC also does not allow removing blocks older than the last federation block.
