### ISSUE TITLE
[Proposal] Make the Block header has a multipurpose field.

### ISSUE THREAD

**Issue by rantan** [chaintope/tapyrus-core#66]
Make the Block header has a multipurpose field. Aggregated Public key field in header is going to be hosted in the multipurpose field. This field also would be able to host any information. We assume the one of the purpose is announcements which is about  activation something of features.

We name the field as `xfield`. This means shorten of `extra field`.

# New Block Header Structure

Name | Type | Size(Bytes) | Description
------|------|-------------|-------------
Version | int32_t | 4 | Block version number. Current block version is 1.
hasPrevBlock | char\[32\] | 32 | 256-bit hash of the previous block header
hashMerkleRoot | char\[32\] | 32 | 256-bit MerkleRoot based on the hashes of all the transactions in the block
hashImMerkleRoot | char\[32\] | 32 | 256-bit MerkleRoot based on Tapyrus transaction id -  [Malleability fixing transaction hash](doc/fix_transaction_malleability.md)
time | uint32_t | 4 | Current block timestamp as seconds since 1970-01-01T00:00 UTC
**xfieldType** | uint8_t | 1 | Type of xfield. see xfieldType table.
**xfield** | specified by xfieldType | variable length | Extra field. This field can host any type of data defined in Tapyrus protocol.
Proof | char[64] | 65* | Threshold signature generated by tapyrus-signer to validate/approve this block. This fields is empty before the block is approved.

* *Additional 1 byte for length

## xfieldType

Value | Name | Type | Size(Bytes) | Description 
----- | ------ | ----- | ------------ | ------------
0x00 | None | N/A | 0 | set when xfield isn't used.
0x01 | AggregatePublicKey | [VarInt](https://en.bitcoin.it/wiki/Protocol_documentation#Variable_length_integer) + char[33] | 34 |  Aggregate public key of tapyrus-signer used to verify block proof. 

All xfield except None must consist of length part and value part. The type of the length part is [VarInt](https://en.bitcoin.it/wiki/Protocol_documentation#Variable_length_integer) and it represents the length of the value part.

# QA

## How to set multiple xfield into a block header?

You can't do it into single block header. This can be done by dividing it into two blocks.

**Comment by azuchi** [comment]
I think `xfieldType` should be uint8_t, instead of char.

**Comment by rantan** [comment]
> I think `xfieldType` should be uint8_t, instead of char.

Ok, i've updated.

**Comment by Yamaguchi** [comment]
I think multiple fields should be able to be included.
you are planning to add the Array type to xfieldType field?

**Comment by rantan** [comment]
I was thinking that the block header can host only one xfield now.

Do you think the block header should host multiple xfield?

**Comment by Yamaguchi** [comment]
For example, suppose that a new feature has been added that "allows the generation interval of blocks to be changed if the signers agrees".

With this feature, you can use the
"From block 100, we should change the block generation interval to 60 minutes."

At the same time,
"From block 100, we should change the federation."
How do we create the 99th block with only one field?

**Comment by rantan** [comment]
I think it is acceptable with single xfield by splitting to two blocks for each condition. 
I will add this case in spec.

**Comment by azuchi** [comment]
@rantan Since the old node can parse block header with an unknown xfield type, we need to add the length of the xfield.

**Comment by rantan** [comment]
@azuchi I updated for the concern of xfield length.
